#!/bin/sh
# Start/stop the cron daemon.
#
### BEGIN INIT INFO
# Provides:          cron
# Required-Start:    $remote_fs $syslog $time
# Required-Stop:     $remote_fs $syslog $time
# Should-Start:      $network $named slapd autofs ypbind nscd nslcd winbind
# Should-Stop:       $network $named slapd autofs ypbind nscd nslcd winbind
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Regular background program processing daemon
# Description:       cron is a standard UNIX program that runs user-specified 
#                    programs at periodic scheduled times. vixie cron adds a 
#                    number of features to the basic UNIX cron, including better
#                    security and more powerful configuration options.
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/opt/oauth2
DESC="oauth2_proxy daemon"
NAME=oauth2_proxy
DAEMON=/opt/oauth2/oauth2_proxy
PIDFILE=/var/run/oauth2_proxy.pid
SCRIPTNAME=/etc/init.d/"$NAME"

# Source function library.
. /lib/lsb/init-functions

case "$1" in
start)	log_daemon_msg "Starting oauth2_proxy" "oauth2_proxy"
        start_daemon -p $PIDFILE $DAEMON -config /opt/oauth2/oauth2_proxy.cfg > /dev/null 2>&1&
        log_end_msg $?
	;;
stop)	log_daemon_msg "Stopping oauth2_proxy" "oauth2_proxy"
        killproc -p $PIDFILE $DAEMON
		killall -s 9 oauth2_proxy
        RETVAL=$?
        [ $RETVAL -eq 0 ] && [ -e "$PIDFILE" ] && rm -f $PIDFILE
        log_end_msg $RETVAL
    ;;
restart) log_daemon_msg "Restarting oauth2_proxy" "oauth2_proxy"
        $0 stop
        $0 start
        ;;
esac
exit 0