#!/bin/sh
#
# WildFly control script
#
# chkconfig: - 80 20
# description: WildFly startup script
# processname: wildfly
# pidfile: /var/run/wildfly/wildfly.pid
# config: /etc/default/wildfly.conf
#

# Source function library.
. /etc/init.d/functions
start() {
	nohup /opt/wildfly/bin/standalone.sh & > /dev/null 2>&1&
	success
	echo
	return 0
}

stop() {
	kill -s 9 $( ps ax | grep java | grep jboss | awk '{print $1 }' )
	success
	echo
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		$0 stop
		$0 start
		;;
	*)
		## If no parameters are given, print which are avaiable.
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
